language: node_js

node_js:
  - 'node'

branches:
  only:
  - master
  - develop
  - /^release-.*/

install:
  - git config --global user.email "build@travis-ci.com"
  - git config --global user.name "Travis CI"
  # we should be able to take this from env var
  - GH_REPO="github.com/apiel/test-crawler.git"

script:
  - cd packages/example-travis
  - yarn
  - yarn start > /dev/null &
  - sleep 5
  - yarn test:crawler:cli

# only push change if found diff
after_failure:
  - git checkout ${TRAVIS_BRANCH}
  - git add .
  - git commit -m "travis commit, test-crawler [ci skip]"
  - git pull
  - git push "https://${GITHUB_TOKEN}@${GH_REPO}" ${TRAVIS_BRANCH} > /dev/null 2>&1 # should always escape output, for security issue, else token could be visible
