language: node_js

node_js:
  - 'node'

branches:
  only:
  - master
  - develop
  - /^release-.*/

install:
  - git config --global user.email "build@travis-ci.com"
  - git config --global user.name "Travis CI"
  - GH_REPO="github.com/${USER}/${REPO}.git"

script:
  - cd packages/example-travis
  - yarn
  - yarn start > /dev/null &
  - sleep 5
  - yarn test:crawler:cli
  - echo "${GH_REPO}"
  - git checkout ${TRAVIS_BRANCH} # instead should be the branch triggering the build
  - git add .
  - git commit -m "travis commit, test-crawler [ci skip]"
  # - git push "https://${GITHUB_TOKEN}@${GH_REPO}" ${TRAVIS_BRANCH} > /dev/null 2>&1

# if diff we should throw an error