language: node_js

node_js:
  - 'node'

branches:
  only:
  - master
  - develop
  - /^release-.*/

install:
  - git config --global user.email "build@travis-ci.com"
  - git config --global user.name "Travis CI"

script:
  - cd packages/example-travis
  - yarn start > /dev/null &
  - sleep 30
  - yarn test:crawler:cli
  - git checkout master # instead should be the branch triggering the build
  - git add .
  - git commit -m "travis commit, test-crawler [ci skip]"
# need to provid credential from env variable
#  - git push

# if diff we should throw an error