language: node_js

node_js:
  - 'node'

branches:
  only:
  - master
  - develop
  - /^release-.*/

install:
  - git config --global user.email "build@travis-ci.com"
  - git config --global user.name "Travis CI"

script:
  - uptime > travisTest.txt
  - git add ./travisTest.txt
  - git commit -m "travis commit [ci skip]"
  - git push