export declare function pathProjectsFolder(): string;
export declare function pathQueueFolder(projectId: string, timestamp: string): string;
export declare function pathQueueFile(projectId: string, timestamp: string, id: string): string;
export declare function pathSiblingFile(projectId: string, timestamp: string, id: string): string;
export declare function pathCrawlFolder(projectId: string): string;
export declare function pathResultFolder(projectId: string, timestamp: string): string;
export declare function pathCrawlerFile(projectId: string, timestamp: string): string;
export declare function pathInfoFile(projectId: string, timestamp: string, id: string): string;
export declare function pathSnapshotFolder(projectId: string): string;
export declare function pathImageFile(projectId: string, timestamp: string, id: string): string;
export declare function pathSourceFile(projectId: string, timestamp: string, id: string): string;
export declare function pathPinInfoFile(projectId: string, id: string): string;
export declare function pathProjectFile(projectId: string): string;
export declare function pathCodeJsFile(projectId: string, id: string): string;
export declare function pathCodeListFile(projectId: string): string;
